### ISSUE TITLE
How to run examples that have static inner classes?

### ISSUE THREAD

**Issue by siddhsql** [langchain4j/langchain4j-examples#10]
Hello, I see many examples in this codebase that use static inner classes. E.g. here:
https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/embedding/classification/EmbeddingModelTextClassifierExample.java

How can I e.g., run the main method inside Pre_Packaged_In_Process_Embedding_Model_Example? I tried

```
mvn exec:java -Dexec.mainClass=embedding.model.InProcessEmbeddingModelExamples.Pre_Packaged_In_Process_Embedding_Model_Example
```

but it gives me:

```
java.lang.ClassNotFoundException: embedding.model.InProcessEmbeddingModelExamples.Pre_Packaged_In_Process_Embedding_Model_Example
    at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass (URLClassLoaderBuilder.java:198)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:521)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:271)
    at java.lang.Thread.run (Thread.java:1623)
```

there are many other variations I tried but all of them give error.

**Comment by siddhsql** [comment]
to answer my own question this works:

```
mvn exec:java -Dexec.mainClass='embedding.model.InProcessEmbeddingModelExamples$Pre_Packaged_In_Process_Embedding_Model_Example'
```

but only if you mark `Pre_Packaged_In_Process_Embedding_Model_Example` as `public` which is not there in the original code so I am still looking if there is a way to execute the `main` method in the inner class without having to modify the original code

**Comment by langchain4j** [comment]
Hi @siddhsql thanks for pointing this out, we will try to reorganize examples without inner classes.
