### ISSUE TITLE
How to get the correct tokenizer for use with InProcessEmbeddingModel(ALL_MINILM_L6_V2)?

### ISSUE THREAD

**Issue by siddhsql** [langchain4j/langchain4j-examples#11]
I'd like to use this code from `langchain4j-examples/other-examples/src/main/java/ChatWithDocumentsExamples.java`:

```
DocumentSplitter splitter = DocumentSplitters.recursive(100, new OpenAiTokenizer(GPT_3_5_TURBO));
            List<TextSegment> segments = splitter.split(document);
```

but I want to use the tokenizer corresponding to `ALL_MINILM_L6_V2` as I want to later on embed the text segments using:

```
EmbeddingModel inProcessEmbeddingModel = new InProcessEmbeddingModel(ALL_MINILM_L6_V2);
```

I understand I have to use the matching tokenizer. how can I get the correct tokenizer for use with `ALL_MINILM_L6_V2`?

**Comment by Morphus1** [comment]
https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

```
# Load model from HuggingFace Hub
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')
model = AutoModel.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')
```

**Comment by langchain4j** [comment]
@siddhsql sorry for the late response. `BertTokenizer` is the one corresponding to `ALL_MINILM_L6_V2`. But usually people would use the tokenizer corresponding to the language model they plan to use. So if you want to make sure retrieved segments will fit into the context window of gpt-3.5, you need to use `new OpenAiTokenizer(GPT_3_5_TURBO)` for splitting.
