### ISSUE TITLE
`demo` API key not working with Streaming example

### ISSUE THREAD

**Issue by lordofthejars** [langchain4j/langchain4j-examples#18]
I am running the examples from this repo, when using the `demo` API key with not streaming examples, it works perfectly, when I executed the streaming examples I got:

```
2023-10-10 16:05:31,521 ERROR [org.acm.StreamingResource$1] (OkHttp https://api.openai.com/...) {
    "error": {
        "message": "Incorrect API key provided: demo. You can find your API key at https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}
```

So maybe this key is only valid when not used in streaming mode?

**Comment by langchain4j** [comment]
Hi @lordofthejars right, streaming is not supported (yet) for demo key, please use your own key for the moment.

**Comment by ZPZP1** [comment]
demo key not support tool calling?

**Comment by langchain4j** [comment]
@ZPZP1 no, not yet

**Comment by langchain4j** [comment]
Closing this issue, please track it [here](https://github.com/langchain4j/langchain4j/issues/926) and [here](https://github.com/langchain4j/langchain4j/issues/927).
