### ISSUE TITLE
Float numbers in Embeddigs

### ISSUE THREAD

**Issue by JM1nd** [langchain4j/langchain4j-examples#24]
I noticed that Embeddings got from HuggingFaceEmbeddingModel return float vector. But float can store 7 decimal digits. How can I get vector with higher accuracy?

**Comment by langchain4j** [comment]
Hi @JM1nd, do you face a loss in precision? 7 decimal places should be more than enough for embeddings, the rest is just noise.

**Comment by JM1nd** [comment]
Hi @langchain4j, I used python langchain libriry to get embeddings. These embeddings are more accurate - 17 decimal places. I have trained my ANN with this values. Then I want to use same in Java. Thats why I expect higher accuracy.

**Comment by langchain4j** [comment]
@JM1nd but do you actually see a loss in accuracy when doing retrieval?
