### ISSUE TITLE
Update spring boot sample to the latest version

### ISSUE THREAD

**Issue by sbouhaddi** [langchain4j/langchain4j-examples#31]
Hello,
Can you please update the examples to use the latest version of langchain4j.
Specially the loadDocument part since it changed a lot in the latest release 

Thank you

**Comment by langchain4j** [comment]
Hi, it was updated during release, please pull

**Comment by sbouhaddi** [comment]
Yes done !
Thank you

**Comment by sbouhaddi** [comment]
Update Done
