### ISSUE TITLE
How to load multiple embedding files?

### ISSUE THREAD

**Issue by mateusscheper** [langchain4j/langchain4j-examples#33]
In [ChatWithDocumentsExamples](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ChatWithDocumentsExamples.java), it's shown how to embed files. But in my case, I'm processing multiple files at different times, which means that I have `embedding_file_1.json`, `embedding_file_2.json`, and so on. 
How to load them all? 

```
Path path = Paths.get(embeddingsPath, embeddingFileName);
InMemoryEmbeddingStore<TextSegment> embeddingStore
    = InMemoryEmbeddingStore.fromFile(path); // It's a single file, but I need more than one
```

Thanks!

**Comment by langchain4j** [comment]
HI @mateusscheper, `InMemoryEmbeddingStore.fromFile(path)` is used for deserializing in-memory embedding store that was previously serialized by calling `inMemoryEmbeddingStore.serializeToFile(path)`. This is an easy way to persist in-memory embedding store if you need persistance but don't want to use external embedding stores like Pinecone or Chroma.

If you have multiple files to embed, you can load them using one of our loaders (or manually), for example: `FileSystemDocumentLoader.loadDocument()` or `FileSystemDocumentLoader.loadDocuments()`.

Then you usually need to split `Document`s into `TextSegment`s using `DocumentSplitter`, then embed `TextSegment`s using `EmbeddingModel` and finally save `Embedding`s into `EmbeddingStore`.

To simplify the process, it is advisable to use `EmbeddingStoreIngestor` as shown in [ChatWithDocumentsExamples](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ChatWithDocumentsExamples.java).

Once you created `EmbeddingStoreIngestor`, you can ingest multiple documents:
- `embeddingStoreIngestor.ingest(document)`
- or `embeddingStoreIngestor.ingest(document1, document2, etc)`
- or `embeddingStoreIngestor.ingest(List.of(document1, document2, etc))`.

Hope this helps.

**Comment by langchain4j** [comment]
If I misunderstood your question and you created multiple `InMemoryEmbeddingStore` (one store per file) and want to merge them during deserialization, there is no way right now. But you can always add more embeddings to the existing `InMemoryEmbeddingStore` and serialize it again.

**Comment by langchain4j** [comment]
May I ask you why do you keep them in a separate files?
If you want the ability to load multiple files at once, we can add a static method like `InMemoryEmbeddingStore<T> fromFiles(Path... files)`.
I would prefer to keep internals of `InMemoryEmbeddingStore` ensapsulated and not expose them via `getEntries()`.

**Comment by mateusscheper** [comment]
Loading multiple files at once would be useful. 

In my case, I can upload a document to the server, extract its text, split into segments, embed them and then store the embeddings to my_file.json. But since I can upload multiple files separately (one at a time), I need to keep their embeddings separated, since I can later change one of the files and embed it again. 
Basically, I don't want to mess with any of other files when dealing with the document I'm changing, but I still need to load all the embeddings into store to use when calling the AI.

**Comment by langchain4j** [comment]
Hi @mateusscheper 

There will be a [way to merge multiple in-memory embedding stores](https://github.com/langchain4j/langchain4j/pull/723).

Loading multiple files at once is also [supported](https://github.com/langchain4j/langchain4j-examples/blob/b01302b6d4c8e3bbb33c12d91a17782a9900b435/other-examples/src/main/java/DocumentLoaderExamples.java) now.

If you need to apply strict filters when searching in embedding store, this is also [supported](https://github.com/langchain4j/langchain4j/pull/610).

I am closing this issue, but feel free to [reopen in the main repo](https://github.com/langchain4j/langchain4j/issues/new/choose) if needed.
