### ISSUE TITLE
Trying to include document sources to answer

### ISSUE THREAD

**Issue by Toumani** [langchain4j/langchain4j-examples#46]
Hello,

I'm trying to have the source of the document(s) used to provide an answer after providing multiple documents (RAG). I don't know how to use LangChain (in Python) but I saw some solutions where they manage to include sources to answer.

There is notably this code from this [StackOverflow answer](https://stackoverflow.com/a/77227515):

```python
qa = ConversationalRetrievalChain.from_llm(
    llm,
    retriever,
    condense_question_prompt=CUSTOM_QUESTION_PROMPT,
    memory=memory,
    return_source_documents=True
)

query = "what are cars made of?"
result = qa({"question": query})
```

Is there something equivalent in the LangChain4j API?

Thanks.

**Comment by langchain4j** [comment]
Hi @Toumani, there is no out-of-the-box support for this yet, but we should definitely add it asap.
You can do this manually at the moment.
Please take a look at [this](https://github.com/langchain4j/langchain4j/pull/538).
You could wrap a `ContentInjector` with a proxy and have access to the list of contents that is injected into the message (prompt).
Something like this:

```java
    class ContentInjectorProxy implements ContentInjector {

        private final ContentInjector delegate;

        ContentInjectorProxy(ContentInjector delegate) {
            this.delegate = delegate;
        }

        @Override
        public UserMessage inject(List<Content> contents, UserMessage userMessage) {
            // you can do whatever you want with "contents"
            return delegate.inject(contents, userMessage);
        }
    }

ContentInjector contentInjector = new ContentInjectorProxy(new DefaultContentInjector());

RetrievalAugmentor retrievalAugmentor = DefaultRetrievalAugmentor.builder()
                .contentRetriever(contentRetriever)
                .contentInjector(contentInjector)
                .build();
```
Then use this `retrievalAugmentor` in `AiServices` or `ConversationalRetrievalChain`.
Ugly, but doable.

**Comment by langchain4j** [comment]
[This example](https://github.com/langchain4j/langchain4j-examples/blob/main/rag-examples/src/main/java/_05_Advanced_RAG_with_Metadata.java) might be also of interest. It shows how to include document source or other metadata fields into the prompt, so that LLM has access to this info.

**Comment by Toumani** [comment]
Thank you for your answer.

Unfortunately, I couldn't locate the relevant classes. I can´t resolve the `dev.langchain4j.rag` package
Is there a Maven dependency I am missing? Here's my `pom.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>chat-bot-api</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>chat-bot-api</name>
	<description>chat-bot-api</description>
	<properties>
		<java.version>17</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j</artifactId>
			<version>0.23.0</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-azure-open-ai</artifactId>
			<version>0.25.0</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-cohere</artifactId>
			<version>0.26.1</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-embeddings-all-minilm-l6-v2</artifactId>
			<version>0.25.0</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by langchain4j** [comment]
It is in `0.26.1` version, it was released just yesterday

**Comment by langchain4j** [comment]
Please update all your dependencies to 0.26.1

**Comment by Toumani** [comment]
Done! I had it working.

Many thanks for the support!

**Comment by langchain4j** [comment]
@Toumani would you mind sharing your code? Curious how you've implemented it!

**Comment by Toumani** [comment]
I noticed that with this version `0.26.1`,  `FileSystemDocumentLoader.loadDocument` would take a document parser as argument and there seem not to be any for PDF and Word documents. I precise that PDF and Word document were supported straight out of the box in previous versions.

**Comment by langchain4j** [comment]
@Toumani PDF and Word parsers were extracted into their own modules, to reduce the number of transitive dependencies of the main module. Please import them separately: https://github.com/langchain4j/langchain4j/tree/main/document-parsers

**Comment by langchain4j** [comment]
Closing this issue, please follow this one in the main repo: https://github.com/langchain4j/langchain4j/issues/660
