### ISSUE TITLE
I want to implement the equivalent in langchain4j of the Python langchain load_qa_chain function for RAG

### ISSUE THREAD

**Issue by caosDvlp** [langchain4j/langchain4j-examples#49]
Hi!

I'm building an app using langchain4j and I want to use the RAG approach. I already have my embeddings and document text data saved in my postgresql with pgvector DB.

Now I'm retrieving that data by the user query, but once I have the user question and the retrieved data from the DB. How can I do the call to Bedrock claude model using langchain4j?

This is the test function I did in Python to test this and is working good

`def handle_userinput(user_question, selected_user):
    bot_template = "BOT : {0}"
    user_template = "USER : {0}"
    try:

        embeddings = BedrockEmbeddings(model_id="amazon.titan-embed-text-v1", region_name="us-east-1")

        conn = psycopg2.connect(DB_CONNECTION_STRING)
        embedding = embeddings.embed_query(user_question)

        cur = conn.cursor()
        print("Selected user:", selected_user)
        cur.execute(f"""
                    SELECT document_text,  1 - (embedding <=> '{embedding}') AS cosine_similarity
                    FROM public.tb_ctz_user_data_embeddings WHERE user_id = %s
                    ORDER BY cosine_similarity desc
                    LIMIT 10
                """, (selected_user,))
        conn.commit()

        # Fetch all rows from the query result
        rows = cur.fetchall()

        # Extract document_text from each row
        document = []
        if rows:
            for item in rows:
                page = Document(page_content=item[0])
                document.append(page)

        # input_documents = [Document(row[0]) for row in rows]
        print("Documentos obtenidos:", document)
        llm = Bedrock(model_id="anthropic.claude-v2", region_name="us-east-1")
        llm.model_kwargs = {"max_tokens_to_sample": 4000, "temperature": 0.0}
        chain = load_qa_chain(llm, chain_type="stuff")
        # Call to the model
        # response = st.session_state.conversation({'question': user_question})
        response = chain.run(input_documents=document, question=user_question)

        print("Response", response)
    except ValueError as e:
        st.write(e)
        st.write("Sorry, please ask again in a different way.")
        return
    st.session_state.chat_history = response
    st.write(user_template.replace("{0}", user_question))
    st.write(bot_template.replace("{0}", response))`

As you can see in this function 

`response = chain.run(input_documents=document, question=user_question)`

Im sending the data found in the DB, and the user answered question to the AI model with **chain.run**.

Now I want to do the same thing in Java with SpringBoot and langchain4j, I followed this example you have

[RAG Example](https://github.com/langchain4j/langchain4j-examples/blob/main/rag-examples/src/main/java/_01_Naive_RAG.java)

But I'm not getting the results I need. There is another way to do this? Or do you have still to implement this feature? Or maybe I'm doing it wrong.

Here is my Java code

`private CustomerSupportAgent createCustomerSupportAgent(PromptDTO promptDto) {

        String userId = promptDto.getUserId();
        String userQuestion = promptDto.getText();
        float[] userQuestionEmbedding = embedComponent.getVectorsFromText(userQuestion);
        List<String> documentTexts =
                userPrivateDataEmbeddingsRepository.findByEmbeddingSimilarityAndDocumentIds(userQuestionEmbedding,
                        embeddingRegistryService.getDocumentIds(UUID.fromString(userId)));
        List<TextSegment> textSegments = documentTexts.stream()
                .map(document -> new TextSegment(document, new Metadata()))
                .collect(Collectors.toList());

        List<Embedding> embeddings = bedrockTitanEmbeddingModel.embedAll(textSegments).content();

        EmbeddingStore<TextSegment> embeddingStore = new InMemoryEmbeddingStore<>();

        embeddingStore.addAll(embeddings, textSegments);

        ContentRetriever contentRetriever = EmbeddingStoreContentRetriever.builder()
                .embeddingStore(embeddingStore)
                .embeddingModel(bedrockTitanEmbeddingModel)
                .maxResults(2) // on each interaction we will retrieve the 2 most relevant segments
                .minScore(0.1) // we want to retrieve segments at least somewhat similar to user query
                .build();

        ChatMemory chatMemory = MessageWindowChatMemory.withMaxMessages(10);

        return AiServices.builder(CustomerSupportAgent.class)
                .chatLanguageModel(bedrockAnthropicChatModel)
                .contentRetriever(contentRetriever)
                .chatMemory(chatMemory)
                .build();
    }`
    
    And then the call to the previous function is being done like this

`CustomerSupportAgent agent = createCustomerSupportAgent(promptDto);

            String answer = agent.answer(promptDto.getText());`

If you could help me guys achieving this approach I will really appreciate it!

Thank you! :)

**Comment by caosDvlp** [comment]
An update here

I use the annotations like this and now it seems to be working fine as it is only answering about the known data on my DB 

`interface CustomerSupportAgent {

        @SystemMessage("Try to answer the user question: {{question}}")
        @UserMessage("Use the followin\n" +
                "g pieces of context to answer the question at the end. If you don't know the answer, " +
                "just say that you don't know, don't try to make up an answer.\\n\\n{{context}}\\n\\n")
        String answer(@V("context") List<Document> context, @V("question") String question);
    }`

Either way, I would appreciate if you guys could tell me if this is the right way to do it, or if it is a better way to do it.

Thanks!

**Comment by langchain4j** [comment]
@caosDvlp I guess we had a discussion with you on discord, right? Do you still need this issue opened?

**Comment by caosDvlp** [comment]
Hi! yeah we discussed about this on Discord, I will close the issue ;)
Thanks man!
