### ISSUE TITLE
java.net.ConnectException: Failed to connect to api.openai.com/199.59.150.12:443

### ISSUE THREAD

**Issue by jingsewu** [langchain4j/langchain4j-examples#5]
When I run this unit test : should_provide_booking_details_and_explain_why_cancellation_is_not_possible , 
I found this error 
**java.lang.RuntimeException: java.net.ConnectException: Failed to connect to api.openai.com/199.59.150.12:443**

But I test this url: api.openai.com on my postman, And it connect successed.

![image](https://github.com/langchain4j/langchain4j-examples/assets/29349667/dc41ccc2-b54f-4da3-8608-c33f45214fb8)

I think may be the VPN is the cause . so  I add this code in my test 
`       System.setProperty("https.proxyHost", "127.0.0.1");   
        System.setProperty("https.proxyPort", "1080");`

It doesn't work.
And I checked the source code and found it use OkHttpClient , It may not use these proxy properties.
So I want to know how to proxy?

**Comment by jingsewu** [comment]
Add more:
I create a OkHttpClient Bean , but it did not work too.
```
    @Bean
    public OkHttpClient okHttpClient() {
        return new OkHttpClient.Builder()
                // Configure the proxy
                .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 1080)))
                .build();
    }
```

**Comment by langchain4j** [comment]
@jingsewu which OpenAI API key are you using? "demo"? or your own?

**Comment by langchain4j** [comment]
@jingsewu we've added an option to specify a proxy for all `OpenAi*Model` classes in 0.20.0:

```
OpenAiEmbeddingModel.builder()
            .apiKey(System.getenv("OPENAI_API_KEY"))
            .proxy(new Proxy(...))
            .build();
```
