### ISSUE TITLE
How to Implement PgVectorEmbeddingStore correctly when instanciating ContentRetriever?

### ISSUE THREAD

**Issue by caosDvlp** [langchain4j/langchain4j-examples#50]
Hi!

I already have a stack of tables to save my embeddings in my PostgreSQL along with the vector extension.

I build a service to get the AI response using RAG but when I need to build the ContentRetriever is asking me the embeddingStore.
At first use the InMemoryEmbeddingStore to do some test and it worked well. But I want to use the PgVector one.

Since I already have my embeddings ready in my DBs tables, there is a way to use PgVectorEmbeddingStore but avoiding the insertion of the embeddings and texts again into a new table to get after that the response from the AI?
Im already getting the text from my DB querying by the embeddings at first place, and then I want to send the request to the AI with the user question plus the text I previously found in the DB.

Should this table work as a temporary data table? Or should I create my custom implementation of the PgVectorEmbeddingStore? 

Because, when I want to build the ContentRetriever the embeddingStore property cannot be null.

Thank you!

**Comment by ilopezluna** [comment]
@caosDvlp why don't you create your [PgVectorEmbeddingStore](https://github.com/langchain4j/langchain4j/blob/3e432486ffc5cb80861e118cbc974f478c3accfc/langchain4j-pgvector/src/main/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStore.java#L30) updating `findRelevant` as you need?

**Comment by caosDvlp** [comment]
Yeah that is what I though after, but I wanted to know if it was a native way to do it. Then I saw this PR
https://github.com/langchain4j/langchain4j/pull/610

That will be integrated in a week I think that implements the filtering feature.
