### ISSUE TITLE
how to configure / test it in local like LM Studio

### ISSUE THREAD

**Issue by dkarthi1973** [langchain4j/langchain4j-examples#57]
How to run this sample code at Local model by using LM studio/ Jan AI. I have tried spring boot unable to customize the link details for customize provider and model

**Comment by ilopezluna** [comment]
You can define the base url for the OpenAI:
`langchain4j.open-ai.chat-model.base-url=http://localhost:1234/v1/`

I'm assuming you are using default config for LM Studio

**Comment by dkarthi1973** [comment]
Yes LM Studio in local, It is working fine after modify the following properties in application.properties. 
langchain4j.open-ai.chat-model.model-name=local-model
langchain4j.open-ai.chat-model.base-url=http://localhost:1234/v1/
Thanks for your valuable response on time.
