### ISSUE TITLE
Need a pgvector example

### ISSUE THREAD

**Issue by kevintanhongann** [langchain4j/langchain4j-examples#58]
There is no langchain4j example for pgvector and postgres yet.

**Comment by kevintanhongann** [comment]
I had a Langchain4j config in spring boot with this bean

`@Bean
    EmbeddingStore<TextSegment> embeddingStore() {
        return PgVectorEmbeddingStore.builder().host("localhost").port(5432).database("pdfChatterPostgres").user(databaseUsername).password(databasePasswqord).table("embeddings").dimension(384).build();
    }`

what is the table structure of the embeddings table?

is it like this?

`CREATE TABLE IF NOT EXISTS embeddings (
  id SERIAL PRIMARY KEY,
  embedding vector,
  text text,
  created_at timestamptz DEFAULT now()
);`

**Comment by langchain4j** [comment]
Hi, we will add example soon. In the meantime, please take a look at source code / javadoc: 
https://github.com/langchain4j/langchain4j/blob/8f5948b9784c65c6743d4cde6098e2751ab8a881/langchain4j-pgvector/src/main/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStore.java#L90

**Comment by rajadilipkolli** [comment]
Hi @kevintanhongann , I have raised PR #63 . Is this what you are looking for?

**Comment by asad-awadia** [comment]
Do you get the token usage back? I keep getting null

**Comment by langchain4j** [comment]
@asad-awadia `AllMiniLmL6V2EmbeddingModel` does not return token usage, because it is free to use anyway (but we can change that). Why do you need the token usage from `AllMiniLmL6V2EmbeddingModel`?

**Comment by asad-awadia** [comment]
@langchain4j I am using it and want to show how many tokens were consumed when creating the embedding so that I can persist and pass that information along

it would be really helpful if that can be added

**Comment by langchain4j** [comment]
You can call one of `estimateTokenCount()` methods on `AllMiniLmL6V2EmbeddingModel` and get the token count.
For 256 token recommendation, you can implementa that easily using one of `DocumentSplitter`s, for example:
```java
DocumentSplitter splitter = DocumentSplitters.recursive(256, 0, new HuggingFaceTokenizer());
List<TextSegment> segments = splitter.split(document);
// or 
List<TextSegment> segments = splitter.splitAll(documents);
```

But I will also add token count to the `Response`, to make it consistent.

**Comment by asad-awadia** [comment]
@langchain4j btw are these models safe to use from multiple threads? or should each thread create its own local instance?

**Comment by asad-awadia** [comment]
@langchain4j hello friendly ping on above

**Comment by langchain4j** [comment]
@asad-awadia I am not sure about that TBH, I did not test it yet. Can you do a few test runs? Thanks!

**Comment by langchain4j** [comment]
@kevintanhongann example has been added [here](https://github.com/langchain4j/langchain4j-examples/blob/main/pgvector-example/src/main/java/PgVectorEmbeddingStoreExample.java), so I am closing this PR.

@asad-awadia [TokenUsage is now returned](https://github.com/langchain4j/langchain4j-embeddings/pull/18) in version 0.29.1.
