### ISSUE TITLE
[Question] While running rag-examples/_01_Naive_RAG.java, JVM is not shutting down immediately

### ISSUE THREAD

**Issue by sivaprasadreddy** [langchain4j/langchain4j-examples#59]
Hi,
I am running various examples and noticed an interesting behaviour.
While running rag-examples/_01_Naive_RAG.java using "demo" or a real OpenAI API Key, once the user input "exit" the JVM still running for at least 10 seconds and then exit. I see similar behaviour in my own similar examples too.

Is it expected?

**Comment by langchain4j** [comment]
Hi, thanks a lot for reporting!
This seems to be a known "issue" with okhttp as it uses non-daemon threads
and we do not shutdown it explicitly. We plan to migrate away from it quite
soon, so this issue should be resolved "automatically".
