### ISSUE TITLE
When will there be support for cases involving ZhipuAiEmbeddingModel with Redis? Currently, there seem to be some issues with testing.

### ISSUE THREAD

**Issue by hongliangzhang07** [langchain4j/langchain4j-examples#74]
When will there be support for cases involving ZhipuAiEmbeddingModel with Redis? Currently, there seem to be some issues with testing.

**Comment by langchain4j** [comment]
Hi @hongliangzhang07 what issues? Please open an issue [here](https://github.com/langchain4j/langchain4j/issues/new/choose) if you face any issues.
