### ISSUE TITLE
Search only in the documents loaded

### ISSUE THREAD

**Issue by vharish-dev** [langchain4j/langchain4j-examples#75]
In [ChatWithDocumentsExamples](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ChatWithDocumentsExamples.java), it's shown how to embed files. But in my case, I would like to restrict the answers to fetch from only the documents loaded. If question is not relevant with any of the documents loaded, generic message should be displayed saying sorry, I couldn't find an answer.

Please help me in achieving this

**Comment by langchain4j** [comment]
Hi @vharish-dev, I am not sure I understand what you mean. [ChatWithDocumentsExamples](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ChatWithDocumentsExamples.java) demonstrates exactly that: using information only from loaded documents.

I am closing this issue, please open a discussion [here](https://github.com/langchain4j/langchain4j/discussions) or [here](https://discord.gg/JzTFvyjG6R).
