### ISSUE TITLE
Any example that shows how to use a local and private model like vicuna?

### ISSUE THREAD

**Issue by siddhsql** [langchain4j/langchain4j-examples#9]
Hello,

Thanks for providing this library. I looked at some of the examples but they seem to be all using Open AI models. Is there any example that shows how to use a model that runs locally and in private (i.e., no network calls to a remote server like OpenAI)?

**Comment by limyfeel** [comment]
me too，who can help

**Comment by vaiju1981** [comment]
Same here, tired following the on the lines of [langchain4j-embeddings-all-minilm-l6-v2](https://github.com/langchain4j/langchain4j-embeddings/tree/main/langchain4j-embeddings-all-minilm-l6-v2)  but it fails.

**Comment by langchain4j** [comment]
Please check `OllamaChatModelTest` in this repo.
